name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2
        with:
            path: |
                ~/.sonar
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Run Codescan On Push
        continue-on-error: true
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@1.3
        with:
          organization: org-as1
          projectKey: ProjectAS
          login: ${{ secrets.sonarcloud_token }}
          codeScanUrl: https://sonarcloud.io
      - name: Run Codescan On PR
        continue-on-error: true
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@1.3
        with:
          organization: org-as1
          projectKey: ProjectAS
          login: ${{ secrets.sonarcloud_token }}
          codeScanUrl: https://sonarcloud.io
          args: |
            sonar.pullrequest.branch=${{github.head_ref}}
            sonar.pullrequest.base=${{github.base_ref}}
            sonar.pullrequest.key=${{github.event.number}}
      - name: Quality Gate Check
        if: github.event_name == 'pull_request'
        continue-on-error: true
        env:
          TOKEN: ${{ secrets.sonarcloud_token }}
          PR_KEY: ${{github.event.number}}
          PROJECT_KEY: ProjectAS
        run: |
          echo  $(curl -s -u "$TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_KEY")
          qg_status=$(curl -s -u "$TOKEN": "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_KEY" | jq -r '.projectStatus.status')
          echo "QG Script --> Quality Gate status is ${qg_status}"
          if [ "${qg_status}" != "OK" ]; then
            echo "QG Script --> Quality gate is not OK - exiting with error"
            exit 1
            fi
