name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2
        with:
            path: |
                ~/.sonar
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Run Codescan On Push
        if: github.event_name == 'push'
        uses: codescan-io/codescan-scanner-action@master
        with:
          codeScanUrl: https://preview.codescan.io/
          organization: preview-aradhana-org
          projectKey: small-sample1      
          login: a088e3de96a777dbd37d05f44c923ecb8929e3f6
          generateSarifFile: true
      - name: Run Codescan On PR
        if: github.event_name == 'pull_request'
        uses: codescan-io/codescan-scanner-action@master
        with:
          codeScanUrl: https://preview.codescan.io/
          organization: preview-aradhana-org
          projectKey: small-sample1
          login: a088e3de96a777dbd37d05f44c923ecb8929e3f6
          generateSarifFile: true
          args: |
            sonar.branch.name=${{github.head_ref}}
            sonar.branch.target=${{github.base_ref}}
            sonar.branch.type=SHORT
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codescan.sarif
