name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:    # The variables to set for your project and organization
      codescan_org: 'aradhana-test'
      codescan_project_key: '00D5g000005I7VNEA0'
      codescan_token: '9ce7b381966df19303321aaea949368175407f28'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: npm
