name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache files
        uses: actions/cache@v2
        with:
            path: |
                ~/.sonar
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      - name: Run Codescan On Push
        uses: codescan-io/codescan-scanner-action@1.3
        with:
          organization: org-as1
          projectKey: ProjectAS
          login: ${{ secrets.sonarcloud_token }}
          codeScanUrl: https://sonarcloud.io
